### ISSUE TITLE
Add high scores tracking to Avoision

### ISSUE THREAD

**Issue by jaredkrinke** [jaredkrinke/sic1#189]
- [x] Ensure hitting Esc saves the current score, if needed
- [x] Create a place to show the scores -- a new entry in the program inventory
- [x] Show the instructions/high scores after exiting the game
- [x] Show high score in game?
- [X] ~~Add "exit" button to game?~~ The close button on the window is enough
- [x] Display message about high score if highest
